// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFIHrmGiySFbLYtgJd1tb6aUzAVYf9oR0',
    appId: '1:592670449612:web:bb96dfc99cb87cac8e8769',
    messagingSenderId: '592670449612',
    projectId: 'virtualclinic-91d78',
    authDomain: 'virtualclinic-91d78.firebaseapp.com',
    storageBucket: 'virtualclinic-91d78.appspot.com',
    measurementId: 'G-51XY4ELT89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmZIq6itTn3f1e3fGnHySJmQJeksbapL4',
    appId: '1:592670449612:android:741778218746bc058e8769',
    messagingSenderId: '592670449612',
    projectId: 'virtualclinic-91d78',
    storageBucket: 'virtualclinic-91d78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCScvqCdm4Yy0IeT39C8UqhYezUzHz2lDg',
    appId: '1:592670449612:ios:83c2a80d1e7169e08e8769',
    messagingSenderId: '592670449612',
    projectId: 'virtualclinic-91d78',
    storageBucket: 'virtualclinic-91d78.appspot.com',
    iosClientId: '592670449612-6vpcghpaeo99ng04bs19bfmjdqm253fm.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorandpatient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCScvqCdm4Yy0IeT39C8UqhYezUzHz2lDg',
    appId: '1:592670449612:ios:83c2a80d1e7169e08e8769',
    messagingSenderId: '592670449612',
    projectId: 'virtualclinic-91d78',
    storageBucket: 'virtualclinic-91d78.appspot.com',
    iosClientId: '592670449612-6vpcghpaeo99ng04bs19bfmjdqm253fm.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorandpatient',
  );
}
